### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by luke-a-rogers** [luke-a-rogers/mmmTMB#1]
- [ ] Streamline call for time-varying model: currently both time_process (1 or 2) and move_by (1 or 3) are involved; this will also affect the definition of tmb_random and tmb_map

**Comment by luke-a-rogers** [comment]
- [ ] Update and complete as_params() and as_probs() with new index order for movement parameter and movement probability array indices (area x area x ...)
- [ ] Complete simulate_recovered() and simulate_data()
- [ ] Write unit tests for simulation functions
- [ ] Write unit tests for utility functions using simulation functions
- [ ] Write unit tests for fit functions using simulation functions
- [ ] Troubleshoot model template
- [ ] Complete functions to visualize and summarize model output

**Comment by luke-a-rogers** [comment]
- [ ] Improve naming to clarify differences between (a) mov_params_6d with dim = c(na, na, nt, n1, n2, n3); (b) mov_params_5d with dim = c(np, nt, n1, n2, n3); and (c) log_mov_pars_5d with dim = c(np, w, x, y, z ) where w <= nt, x <= n1, y <= n2, z <= n3, and where w depends on time_process while x, y, and z depend on move_by

**Comment by luke-a-rogers** [comment]
- [ ] Replace num_obs in create_recovered_7d() by correct calculation (stepped sum); currently fixed by initializing recovered with NAs and then returning na.omit(recovered)

**Comment by luke-a-rogers** [comment]
- [ ] Check arguments so that bias_by, move_by, and time_process are appropriate for the corresponding array dimensions
- [ ] Fix arrays constant initial index 1 --> 0 after line 142

**Comment by luke-a-rogers** [comment]
- [ ] Update distributions calls to handle zero expected mean

**Comment by luke-a-rogers** [comment]
- [ ] Fit model to coastwide data
    - [ ] All
    - [ ] By size class
    - [ ] By sex
    - [ ] All time-varying
- [ ] Fit model to Meghan BC data
    - [ ] Fishing mortality assumptions (less in inlets)
    - [ ] Bias assumptions
    - [ ] Area configurations

**Comment by luke-a-rogers** [comment]
- [ ] How long should tags be at liberty before recoveries are counted? Implement an argument for
    - [ ] create_recovered_7d()
    - [ ] mmmTMB()
- [ ] Why is the NB2 implementation returning NaN?
- [ ] How many tags move more than one area over in a single time step?
- [ ] Why does the model fit appear much slower?
- [ ] Make use of the map argument to fix parameter values

**Comment by luke-a-rogers** [comment]
Simplify exploratory model fits by:
- [ ] Fitting to annual time step with full - diag template
    - [ ] Should give good first-cut estimates
    - [ ] Much "smaller" data set for the model to handle
    - [ ] Annual time step for the time-varying process
- [ ] Automate fitting in R script and output data frame as table

**Comment by luke-a-rogers** [comment]
- [ ] In validate_model(): make length of capture_bias responsive to fit_bias_by
- [ ] Add vignette sections for 3 area time varying
- [ ] Add vignette sections for 10 area static
- [ ] Add vignette sections for 3 area static release by month
