### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by luke-a-rogers** [luke-a-rogers/mmmTMB#1]
Implementation
- [ ] Arguments for mmmTMB()
    - [ ] Fit to simulated?
    - [ ] Simulation parameters argument: sim_parameters = NULL
    - [ ] Random initial parameters
    - [ ] Arguments to nlminb(): control, ...
- [ ] Add function to return map arrays: 
    - [ ] create_bias_map(): based on bias_by argument
    - [ ] create_deviations_map(): allow frequency n, and repeated cycle of period m
- [ ] Add random effects and map
- [ ] Add tmbstan
- [ ] Output AIC?

Validation
- [ ] Return residuals
- [ ] Plot functions
    - [ ] Static parameters
    - [ ] Time varying movement probability deviations

Package
- [ ] data-raw/
- [ ] tests
- [ ] vignettes
